// <auto-generated />
using System;
using KunFarm.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KunFarm.DAL.Migrations
{
    [DbContext(typeof(KunFarmDbContext))]
    [Migration("20250707040552_AddChickensAndEggsState")]
    partial class AddChickensAndEggsState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KunFarm.DAL.Entities.FarmState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 7, 7, 4, 5, 51, 978, DateTimeKind.Utc).AddTicks(3900));

                    b.Property<string>("PlantsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TileStatesJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FarmStates");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.InventorySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerStateId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerStateId");

                    b.ToTable("InventorySlots");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectableType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.OnlineShopSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<bool>("CanBuy")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantiy")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SellerId");

                    b.ToTable("OnlineShopSlots");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.PlayerRegularShopSlot", b =>
                {
                    b.Property<int>("PlayerStateId")
                        .HasColumnType("int");

                    b.Property<int>("RegularShopSlotId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStock")
                        .HasColumnType("int");

                    b.HasKey("PlayerStateId", "RegularShopSlotId");

                    b.HasIndex("RegularShopSlotId");

                    b.ToTable("PlayerRegularShopSlots");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.PlayerState", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ChickensStateJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("EggsStateJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<float>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100f);

                    b.Property<float>("Hunger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100f);

                    b.Property<DateTime>("LastSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 7, 7, 11, 5, 51, 978, DateTimeKind.Local).AddTicks(880));

                    b.Property<int>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("PosX")
                        .HasColumnType("float");

                    b.Property<float>("PosY")
                        .HasColumnType("float");

                    b.Property<float>("PosZ")
                        .HasColumnType("float");

                    b.HasKey("UserId");

                    b.ToTable("PlayerStates");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.PlayerToolbar", b =>
                {
                    b.Property<int>("PlayerStateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 7, 7, 11, 5, 51, 978, DateTimeKind.Local).AddTicks(3390));

                    b.Property<string>("ToolsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("PlayerStateId");

                    b.ToTable("PlayerToolbars");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.RegularShopSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<bool>("CanBuy")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("StockLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("RegularShopSlots");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.FarmState", b =>
                {
                    b.HasOne("KunFarm.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.InventorySlot", b =>
                {
                    b.HasOne("KunFarm.DAL.Entities.Item", "Item")
                        .WithMany("InventorySlots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KunFarm.DAL.Entities.PlayerState", "PlayerState")
                        .WithMany("InventorySlots")
                        .HasForeignKey("PlayerStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PlayerState");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.OnlineShopSlot", b =>
                {
                    b.HasOne("KunFarm.DAL.Entities.PlayerState", "Buyer")
                        .WithMany("BuyingOnlineShopSlots")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KunFarm.DAL.Entities.Item", "Item")
                        .WithMany("OnlineShopSlots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KunFarm.DAL.Entities.PlayerState", "Seller")
                        .WithMany("SellingOnlineShopSlots")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Buyer");

                    b.Navigation("Item");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.PlayerRegularShopSlot", b =>
                {
                    b.HasOne("KunFarm.DAL.Entities.PlayerState", "PlayerState")
                        .WithMany("PlayerRegularShopSlots")
                        .HasForeignKey("PlayerStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KunFarm.DAL.Entities.RegularShopSlot", "RegularShopSlot")
                        .WithMany("PlayerRegularShopSlots")
                        .HasForeignKey("RegularShopSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerState");

                    b.Navigation("RegularShopSlot");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.PlayerState", b =>
                {
                    b.HasOne("KunFarm.DAL.Entities.User", "User")
                        .WithOne("PlayerState")
                        .HasForeignKey("KunFarm.DAL.Entities.PlayerState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.PlayerToolbar", b =>
                {
                    b.HasOne("KunFarm.DAL.Entities.PlayerState", "PlayerState")
                        .WithOne("PlayerToolbar")
                        .HasForeignKey("KunFarm.DAL.Entities.PlayerToolbar", "PlayerStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerState");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.RegularShopSlot", b =>
                {
                    b.HasOne("KunFarm.DAL.Entities.Item", "Item")
                        .WithOne("RegularShop")
                        .HasForeignKey("KunFarm.DAL.Entities.RegularShopSlot", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.Item", b =>
                {
                    b.Navigation("InventorySlots");

                    b.Navigation("OnlineShopSlots");

                    b.Navigation("RegularShop")
                        .IsRequired();
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.PlayerState", b =>
                {
                    b.Navigation("BuyingOnlineShopSlots");

                    b.Navigation("InventorySlots");

                    b.Navigation("PlayerRegularShopSlots");

                    b.Navigation("PlayerToolbar");

                    b.Navigation("SellingOnlineShopSlots");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.RegularShopSlot", b =>
                {
                    b.Navigation("PlayerRegularShopSlots");
                });

            modelBuilder.Entity("KunFarm.DAL.Entities.User", b =>
                {
                    b.Navigation("PlayerState");
                });
#pragma warning restore 612, 618
        }
    }
}
