version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: KunFarm.Presentation/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;user=root;password=root;database=Kun_Farm;
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Kun_Farm
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
