# Stage 1: Base image for runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

# Stage 2: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy toàn bộ source
COPY . .

# Copy riêng file cấu hình production nếu có
COPY ./KunFarm.Presentation/appsettings.Production.json ./KunFarm.Presentation/appsettings.Production.json

# Restore packages
RUN dotnet restore ./KunFarm.Presentation/KunFarm.Presentation.csproj

# Publish
RUN dotnet publish ./KunFarm.Presentation/KunFarm.Presentation.csproj -c Release -o /app/publish

# Stage 3: Final runtime image
FROM base AS final
WORKDIR /app

# Copy kết quả publish từ stage build
COPY --from=build /app/publish .

# Run
ENTRYPOINT ["dotnet", "KunFarm.Presentation.dll"]
