version: '3.8'
services:
  app:
    image: ${DOCKER_USERNAME}/kunfarm-api:latest
    ports:
      - "5270:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=server=mysql;port=3306;user=root;password=${MYSQL_ROOT_PASSWORD};database=Kun_Farm;
    restart: unless-stopped
    networks:
      - kunfarm-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: Kun_Farm
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 10s
    restart: unless-stopped
    networks:
      - kunfarm-network

volumes:
  mysql-data:

networks:
  kunfarm-network:
    driver: bridge 